language: rust
sudo: required
os:
- linux
- osx
rust:
- stable
services:
- docker
before_script:
  - rustup component add rustfmt
  - rustup component add clippy
script:
  # Require `cargo fmt` to have been run.
  - cargo fmt -- --check
  # Require clippy to pass without warnings. This also fails for regular Rust
  # warnings.
  - cargo clippy -- -D warnings
  # Build the code.
  - cargo build --verbose
  # Run the tests.
  - cargo test --verbose
before_deploy: "./build-release cage ${TRAVIS_TAG}-${TRAVIS_OS_NAME}"
deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file_glob: true
  file: "cage-${TRAVIS_TAG}-${TRAVIS_OS_NAME}.*"
  skip_cleanup: true
  on:
    rust: stable
    tags: true
